name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:       
    - name: Kết nối ssh linux -> và pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /var/www/quy_projectmd2/PROJECT_MODULE2_SERVER
          pm2 delete all
          git pull
          git status
          . $HOME/.nvm/nvm.sh
          nvm use
          npm ci
          npx prisma generate
          pm2 start npm --name "project2_sever" -- run dev
          
